### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by Priz001** [RogerioBlanco/PixelCanvasBot#103]
![image](https://user-images.githubusercontent.com/33595635/79771836-a4372380-832f-11ea-8adf-f906efac90ba.png)

I have problems with the setup, how can i fix this?

**Comment by dtat1488** [comment]
reinstall pythone 2.7 again and make sure that the checkbox for installing pip is checked (it is per default)

**Comment by Priz001** [comment]
It's working now thanks. I also have to delete the main PixelCanvasBot directory
