### ISSUE TITLE
Already painted pixel

### ISSUE THREAD

**Issue by Priz001** [RogerioBlanco/PixelCanvasBot#104]
It doesn't detects already painted pixels, and overpaints it.

(Edit: Also with --colors_not_overwrite function it paints on)

**Comment by Priz001** [comment]
It paints over with brc trc cpd... strategies

**Comment by dtat1488** [comment]
i keep reading that but i can't reproduce it, do you have the log?

**Comment by Priz001** [comment]
C:\Users\user\Desktop>cd PixelCanvasBot-master

C:\Users\user\Desktop\PixelCanvasBot-master>main.py -f 674a9cc3c09dc28e6791bf740ca88465 -i Hooligans.png -x -1163 -y -2500 --draw_strategy linear
>> 16:43:10 ->Load cached image
>> 16:43:15 ->Websocket open
>> 16:43:15 ->Waiting 48.106 seconds
[++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 16:44:04 ->You painted white at -1163,-2500
>> 16:44:04 ->Waiting 29.227 seconds
>> 16:44:04 ->Somebody updated -1163,-2500 with white
[

Here it put white on white

**Comment by dtat1488** [comment]
got it and fixed websocket and bot pixels with pull request #105 
If it is setting white on top of white right after starting the bot already, that's another issue however (or you restarted too fast and the bigchunk isn't updated yet).

Please test it and report back.
It also does more logging.

**Comment by dtat1488** [comment]
just in case you don't find it, you can get it here https://github.com/dtat1488/PixelCanvasBot while it's not pulled in here yet

**Comment by Priz001** [comment]
It still overplaces pixels, not only on the first pixel when I start the bot, but also in the next pixels

**Comment by dtat1488** [comment]
Are you on discord?

**Comment by Priz001** [comment]
Yes, Preeze#7029

**Comment by dtat1488** [comment]
now its fixed

**Comment by Priz001** [comment]
Yes, it's perfectly working now
