### ISSUE TITLE
Painting times vary a lot

### ISSUE THREAD

**Issue by DrZeldaGlitch** [RogerioBlanco/PixelCanvasBot#119]
So i've been bothered by how long it takes for a pixel to be drawn even tho the maximum amount of time to wait is 30 seconds (according to pixelcanvas.io by the time of making this issue)

>> 22:28:51 ->Load cached image
>> 22:29:04 ->Websocket open
>> 22:29:04 ->Waiting **54.889** seconds
[++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 22:30:01 ->You painted white at [REDACTED]
>> 22:30:01 ->Waiting **94.18** seconds
>> 22:30:01 ->Somebody updated [REDACTED] with white
[++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 22:31:37 ->You painted white at [REDACTED]
>> 22:31:37 ->Waiting **93.31** seconds
>> 22:31:37 ->Somebody updated [REDACTED] with white
[++++++++++++++++++++++++++++++++++++++++++++++++++]
>> 22:33:11 ->You painted white at [REDACTED]
>> 22:33:11 ->Waiting **93.366** seconds
>> 22:33:11 ->Somebody updated [REDACTED] with white
[++++----------------------------------------------]

is this normal, is it a bug?

**Comment by Computerdores** [comment]
"The Cooldown is 10 seconds for new pixels, and 30 seconds when you replace a pixel, **plus a bonus factor** based on the age of that pixel." -[pixelcanvas.io](pixelcanvas.io)
