### ISSUE TITLE
Error! Line 46

### ISSUE THREAD

**Issue by ZeedyPixel** [RogerioBlanco/PixelCanvasBot#13]
![screenshot_2](https://user-images.githubusercontent.com/29678843/27990664-fe8297ac-6433-11e7-99cb-105cb70e20ed.png)

**Comment by Crashzilla** [comment]
I got this error too. This is probably because you are using a newer version of python. In the newer versions print needs parentheses but in the older ones it didn't. Try downloading python 2.7 if hadn't already.

**Comment by Qh0stM4N** [comment]
It does not seem like a major problem.
I will fix it with sketch strategy pr.

**Comment by ZeedyPixel** [comment]
I've downloaded the python 2.7 and it worked fine. Ty for help

**Comment by RogerioBlanco** [comment]
I will fix this to work in python > 3

**Comment by ZeedyPixel** [comment]
Ok! Good Luck

**Comment by RogerioBlanco** [comment]
Done!
