### ISSUE TITLE
Possible problem with images being "too big"

### ISSUE THREAD

**Issue by Crashzilla** [RogerioBlanco/PixelCanvasBot#14]
Tried to run the script with a couple of big images and always ended up with this error.

![sem titulo](https://user-images.githubusercontent.com/1349727/27991749-efd7e05e-6456-11e7-9794-5e8058256846.png)

The code run smoothly with smaller ones. Tried to find a solution but my knowledge in python is pretty basic. Is there a size limitation?

**Comment by RogerioBlanco** [comment]
Don't have a limit. How big is this images?

**Comment by RogerioBlanco** [comment]
I tested right now with one image with 1600x700 pixels and I don't have any issues. If you can provide more details or the image its will be better.

**Comment by Crashzilla** [comment]
Nothing special with the images. Tried with 3 different ones (1000x403; 1024x721; 1364x768) all being PNG. I even tried to split in half one of they and the script gave me no errors.

**Comment by RogerioBlanco** [comment]
So, with these three images you had no problems?

**Comment by Crashzilla** [comment]
None of they worked. So I splitted they in the half and worked.

**Comment by RogerioBlanco** [comment]
Ah ok, I understand now. I will test more times.

**Comment by RogerioBlanco** [comment]
Fixed
