### ISSUE TITLE
Timelapse option

### ISSUE THREAD

**Issue by ZeedyPixel** [RogerioBlanco/PixelCanvasBot#33]
You could put an option to make an timelapse about the start, the middle and the end of the constrution.

It'll good to see the progress

**Comment by Qh0stM4N** [comment]
I do not know if it's working, but this is a separate project try it
Combining two can result in undesirable results.
for example If the google token is invalid, the bot will allow up to max 1 hour to 2 hours to run but drawing image pixels can take weeks.
So I can recommend using the timelapse tool in a different process.
https://github.com/RogerioBlanco/TimelapsePixelCanvas

**Comment by ZeedyPixel** [comment]
I forgot to say to add the timelapse in the bot, to when you start the bot, the timelapse start too. To after you can see the progress in png. I think it'll cool.

**Comment by RogerioBlanco** [comment]
The other tool, who Qh0stM4N posted is working and functional. This suggestion just will add complexity to the project.
