### ISSUE TITLE
Problem with response.json

### ISSUE THREAD

**Issue by Crashzilla** [RogerioBlanco/PixelCanvasBot#38]
It's been a couple of days that I keep receiving this error. 

It's rather big so i'm putting in an external link: https://wordpad.cc/XkdsvVAZ

As far as I understand that is a problem in the pixelcanvas side but the website is working propely. Do you know what might be happening

**Comment by Qh0stM4N** [comment]
bad paste area pls use https://gist.github.com/ :-1: 

fixed problem #39
