### ISSUE TITLE
The script should play a sound or show some kind of "notification" when user interaction is required

### ISSUE THREAD

**Issue by deniz2694** [RogerioBlanco/PixelCanvasBot#48]
I let the script run in the background but I never know when I need to relaunch it, or when it needs a token, it should notify me when it happens, so I can relaunch the bot the fastest as possible when it stops.

**Comment by RogerioBlanco** [comment]
Make sense, I will implement this functionality

**Comment by deniz2694** [comment]
thanx :]

**Comment by marcussacana** [comment]
i wrote this script before...
```
echo off
start https://pixelcanvas.io/@-0,-0
cls
:again
echo Enter the Fingerprint:
set /p FP=

"C:\python27\Python.exe" main.py -i Draw.png -x -0-y -0--draw_strategy linear -f %FP%
msg * "Pixel Canvas, Token Expired!"
goto again
```

**Comment by ZeedyPixel** [comment]
SOunds will be great, Sometimes I forget to see the console

**Comment by RogerioBlanco** [comment]
It will beep sound 30 times. I implemented this because it's easy and works in linux and windows. (I just tested in Windows).
