### ISSUE TITLE
flood updated messages

### ISSUE THREAD

**Issue by Qh0stM4N** [RogerioBlanco/PixelCanvasBot#5]
problem my test img is only 10 px X 10 px

started bot this coordinates
python ./main.py -i img/loogoo.png -f $fingerprint$ -x 400 -y -2100

but this message no img range
too many messages: It's not useful

> Waiting 65.604 seconds
> Somebody updated 354,-2006 with white color
> Somebody updated 55,-2056 with red color
> Somebody updated 304,-519 with white color
> Somebody updated 84,-359 with nero color
> Somebody updated 100,-660 with green color
> Somebody updated 118,-580 with green color
> Somebody updated 83,-554 with green color
> Somebody updated 475,-153 with blue color
> Somebody updated 412,-434 with red color
> Somebody updated 432,-302 with red color
> Somebody updated 246,-541 with white color
> Somebody updated 117,-538 with white color
> Somebody updated 124,-544 with white color
> Somebody updated 111,-519 with white color
> Somebody updated 122,-519 with white color
> Somebody updated -43,-373 with green color
> Somebody updated 140,-521 with white color
> Somebody updated 134,-521 with white color
> Somebody updated 23,-300 with blue color
> Somebody updated -59,-254 with green color
> Somebody updated 168,-538 with white color
> Somebody updated 118,-580 with white color
> Somebody updated 153,-318 with white color
> Somebody updated 106,-387 with blue color
> Somebody updated 180,-1929 with nero color
> Somebody updated -96,-64 with red color
> Somebody updated -107,-585 with green color
> Somebody updated 193,-2060 with nero color
> Somebody updated 251,-2466 with green color
> Somebody updated 426,-524 with red color
> Somebody updated 160,-536 with white color
> Somebody updated 135,2099 with nero color
> Somebody updated 181,-404 with nero color
> Somebody updated 417,-411 with red color
> Somebody updated 354,-451 with red color
> Somebody updated -102,-232 with blue color
> Somebody updated -122,-65 with blue color
> Somebody updated -42,-228 with carnation pink color
> Somebody updated 212,-254 with white color
> Somebody updated 30,-254 with blue color
> Somebody updated -43,-373 with blue color
> Somebody updated 334,-388 with red color
> Somebody updated 160,-566 with white color
> Somebody updated 306,2666 with nero color
> Somebody updated 136,-521 with white color
> Somebody updated 185,-325 with green color
> Somebody updated 40,2106 with white color
> Somebody updated -65,1499 with green color
> Somebody updated 15,-2035 with red color
> Somebody updated 187,-549 with white color
> Somebody updated -32,-399 with blue color
> Somebody updated 300,-517 with white color
> Somebody updated 134,-520 with white color
> Somebody updated -101,-233 with blue color
> Somebody updated 179,-538 with white color
> Somebody updated 144,-548 with white color
> Somebody updated 286,-515 with white color
> Somebody updated -24,1994 with white color
> Somebody updated 135,-474 with blue color
> Somebody updated 132,-521 with green color
> Somebody updated 146,-425 with white color
> Somebody updated 121,-519 with white color
> Somebody updated 405,-612 with white color
> Somebody updated 118,-552 with white color
> Somebody updated 38,-423 with blue color
> Somebody updated 266,-429 with white color
> Somebody updated 117,-519 with white color
> Somebody updated 107,-232 with green color
> Somebody updated 313,-513 with white color
> Somebody updated 293,-465 with white color
> Somebody updated 353,-448 with yellow color
> Somebody updated 261,-304 with white color
> Somebody updated 233,-538 with green color
> Somebody updated 190,-349 with blue color
> Somebody updated 270,-400 with blue color
> Somebody updated 528,-582 with green color
> Somebody updated 287,-515 with white color
> Somebody updated 131,-520 with white color
> Somebody updated 131,-561 with white color
> Somebody updated 113,-546 with white color
> Somebody updated 827,-2585 with pacific blue color
> Somebody updated 373,-294 with red color
> Somebody updated 284,-525 with white color

**Comment by RogerioBlanco** [comment]
This log will to be default just to the interest area. start_x >= x =< start_x + image.width
and start_y >= y =< start_y + height
