### ISSUE TITLE
Sugestão de defesa.

### ISSUE THREAD

**Issue by ZeedyPixel** [RogerioBlanco/PixelCanvasBot#52]
Acho que ficaria legal também na hora que aparecer uma grande quantidade de pixel diferente da cor original da imagem, o bot dar o aviso apitando igual o do captcha.

**Comment by Qh0stM4N** [comment]
Nothing was understood. Can you convey your idea more clearly

**Comment by RogerioBlanco** [comment]
Isso só é possível se fizermos uma estatística em tempo real de cada pixel que seja colocado em favor da sua imagem. Nós não temos isso, por enquanto.

This is just be possible if we make a statistic in real time of every pixel that is put in favor of your image. We don't have this, for now.

**Comment by ZeedyPixel** [comment]
Sem problemas, foi apenas uma sujestão kkk.

No problems, it was just a suggestion
