### ISSUE TITLE
KeyError: 'waitSeconds'

### ISSUE THREAD

**Issue by dariollo** [RogerioBlanco/PixelCanvasBot#53]
how to fix it?  
```
Load cached image
Traceback (most recent call last):
  File "./main.py", line 62, in <module>
    main()
  File "./main.py", line 58, in main
    run()
  File "./main.py", line 53, in run
    bot.run()
  File "C:\Python27\Lib\PixelCanvasBot\src\bot.py", line 32, in run
    self.wait_time(me)
  File "C:\Python27\Lib\PixelCanvasBot\src\bot.py", line 56, in wait_time
    if data['waitSeconds'] is not None:
KeyError: 'waitSeconds'
>> 03:06:00 ->### closed ### 
```

**Comment by RogerioBlanco** [comment]
You can put this code in line 55 in the bot?
  print(data)
And post the result here.

**Comment by Qh0stM4N** [comment]
i did't seen yours parameter ? The information you give is very inadequate.

**Comment by dariollo** [comment]
`def wait_time(self, data = {'waitSeconds':None}):
        def complete(i, wait):
            return ((100 * (float(i) / float(wait))) * 20) / 100

        if data['waitSeconds'] is not None:
            wait = data['waitSeconds'] + (random.randint(0, 9) / 10.0)
            print(I18n.get('Waiting %s seconds') % str(wait))

            c = i = 0
            while c < 20:
                c = complete(i, wait)
                time.sleep(wait - i if i == int(wait) else 1)
                out.write("[{}]\0\r".format('+' * int(c) + '-' * (20 - int(c))))
                out.flush()
                i += 1
            out.write("\n")
            out.flush()`

**Comment by RogerioBlanco** [comment]
Copy this code below and paste in bot.py:
def wait_time(self, data = {'waitSeconds':None}):
        def complete(i, wait):
            return ((100 * (float(i) / float(wait))) * 20) / 100
        print(data)
        if data['waitSeconds'] is not None:
            wait = data['waitSeconds'] + (random.randint(0, 9) / 10.0)
            print(I18n.get('Waiting %s seconds') % str(wait))

            c = i = 0
            while c < 20:
                c = complete(i, wait)
                time.sleep(wait - i if i == int(wait) else 1)
                out.write("[{}]\0\r".format('+' * int(c) + '-' * (20 - int(c))))
                out.flush()
                i += 1
            out.write("\n")
            out.flush()

**Comment by dariollo** [comment]
nothing really change

**Comment by Qh0stM4N** [comment]
closed Abonded with auther of issue and I think it's not a general problem, it's just a spesific cillent problem.

**Comment by smanganoti** [comment]
I have the same problem. With python 2.7.14.

With print(data) on line 55:

C:\Users\Santiago\PixelCanvasBot>python ./main.py -i foto.png -f $4f029789d9bf560ad12e634724c2b0ee$ -x -183 -y -634
Traceback (most recent call last):
  File "./main.py", line 4, in <module>
    from src.bot import Bot
  File "C:\Users\Santiago\PixelCanvasBot\src\bot.py", line 56
    if data['waitSeconds'] is not None:
    ^
IndentationError: unexpected indent

**Comment by Qh0stM4N** [comment]
reopened this issue #64
