### ISSUE TITLE
Wouldn't just making a .exe be better?

### ISSUE THREAD

**Issue by ECKDEE** [RogerioBlanco/PixelCanvasBot#58]

**Comment by RogerioBlanco** [comment]
Well, at time that bot is created we had a lot of updates. So it's better to install python  to execute and git to have the with last update

**Comment by Qh0stM4N** [comment]
I've already made an improvement to make installation easier. In the past we had to manually install python packages. (see  at #55 ) I prepared a setup.py file for automatic installation of the packages. Even in old python versions which do not have pip internally, I gave priority to doing pip installation first. I believe this development is enough. So I close issue.
