### ISSUE TITLE
new print strategy idea

### ISSUE THREAD

**Issue by Qh0stM4N** [RogerioBlanco/PixelCanvasBot#6]
### my print idea is primarily frame dont fill image. fill image option have a lot of time.

for example
first images convert to twince images and started white color ignored mode
![images](https://user-images.githubusercontent.com/12828465/27822775-2758d10e-60a7-11e7-83b9-b040d75cf641.png)

## how to? 
```
if This colour == Previous color:
     #dont put pixel 
     Previous color = this color
     go next step

else
     #ok put pixel 
     ...
     Previous color = this color
```

this control statlament adding to four strategies

-  left to rigth
- right to left
- top to  bottom
- bottom to top

4 strategies finished ready to frame. go randomize strategies to fill images.
I thing It is more difficult for people to know that this system is a bot.
I will try to include it when I am available

**Comment by RogerioBlanco** [comment]
I understand and agree with this idea. I don't think this is will be difficult to implement. I will make a sketch

**Comment by Qh0stM4N** [comment]
thanks, sketching does not seem hard to coding.
but I just never wrote python before.

**Comment by Qh0stM4N** [comment]
finised from #26

**Comment by Priz001** [comment]
Hey, how can I change the draw strategy? from git? what i have to write? Thanks c:

**Comment by Qh0stM4N** [comment]
@Priz001 add --draw_strategy parameter
for example `--draw_strategy sketch` or `--draw_strategy status`

**Comment by Priz001** [comment]
Turk oldugunu bilmiyordum .D, neyse timer biraz bozuk, ne yapabilirim? Bazen Error veriyor, 5-6 saniye gec atiyor.

**Comment by Qh0stM4N** [comment]
@Priz001 Hata mesjı varmı yeni noktayı koyarken gecikme var zaten rasgele olarak 1 ila 10 saniye daha ekledin bekleme süresinin üzerine. Hata mesajı yakalayabilirsen daha iyi olur.

**Comment by Qh0stM4N** [comment]
bide sorun olmazsa ingilizce yaz çöp ederler burayı ifşa olmayalım.
