### ISSUE TITLE
DLL load failed: %1 is not a viable Win32 application

### ISSUE THREAD

**Issue by MannRodighan** [RogerioBlanco/PixelCanvasBot#62]
![cmd_2017-10-14_15-01-35](https://user-images.githubusercontent.com/32795398/31575903-c1e5aa8c-b0f0-11e7-9654-c9a7aaa011e9.png)

Python version is 2.7.12, also didn't work in 2.7.13. I tried almost everything, maybe you'll be able to help me ?

**Comment by Qh0stM4N** [comment]
hello @MannRodighan need yours OS detail
open cmd paste 'systeminfo' te get result.

**Comment by MannRodighan** [comment]
The whole thing was in french so I did my best to translate it : 


Host name:                              DESKTOP-402H30L
OS name:              Microsoft Windows 10 Family
System Version:                         10.0.15063 N/A version 15063
OS fabricant:        Microsoft Corporation
OS configuration:    Autonomous Workstation
OS Version type:  Multiprocessor Free
Registered owner:                    Utilisateur Windows
Registered company:
Product indentifier:                  00326-00796-72976-AAOEM
Original installation date:              16-04-17, 03:36:54
System starting hour:              14-10-17, 14:06:18
System fabricant:                       Gigabyte Technology Co., Ltd.
System model:                          H270-Gaming 3
System type:                            x64-based PC
Processor(s):                              1 installed processor(s) :
                                            [01] : Intel64 Family 6 Model 158 Stepping 9 GenuineIntel ~3600 MHz
BIOS version:                            American Megatrends Inc. F2, 30-11-16
Windows directory:                         C:\WINDOWS
System directory:                         C:\WINDOWS\system32
Peripheral boot:                    \Device\HarddiskVolume3
Regional system option:                fr-be;Français (Belgium)
Startint regional parameters:              fr-be;Français (Belgium)
Time zone:                             (UTC+01:00) Bruxelles, Copenhague, Madrid, Paris
Total physical memory:                    8.145 Mo
Available physical memory:                3.333 Mo
Virtual memory : maximal size:        22.481 Mo
Virtual memory : available:             15.342 Mo
Virtual memory: being used right now: 7.139 Mo
Trading files locations:        C:\pagefile.sys
Domain:                                    WORKGROUP
Opening session server:             \\DESKTOP-402H30L
Corrective(s):                               3 installed Corrections.
                                            [01]: KB4022405
                                            [02]: KB4038806
                                            [03]: KB4041676
Network card(s):                            3 network cards installed.
                                            [01]: Killer E2500 Gigabit Ethernet Controller
                                                  Connection name : Ethernet
                                                  State :                Support Disconnected
                                            [02]: Realtek RTL8192CE Wireless LAN 802.11n PCI-E NIC
                                                  Connection name : Wi-Fi
                                                  DHCP activated :         Yes
                                                  DHCP server :        192.168.1.1
                                                 IP Addresse(s)
                                                  [01]: 192.168.1.63
                                                  [02]: fe80::f8ec:404b:2c80:24cc
                                                  [03]: 2a02:a03f:4017:e500:1cd9:2939:eed:bd53
                                                  [04]: 2a02:a03f:4017:e500:f8ec:404b:2c80:24cc
                                            [03]: LogMeIn Hamachi Virtual Ethernet Adapter
                                                  Connection name : Hamachi
                                                  State :                Absent material
Required configuration for HyperV:         Extensions of virtual computer monitor : Yes
                                            Activated virtualization in the microprogram : Yes
                                            Second level address traduction : Yes
                                            Available datas execution prevention : Yes

**Comment by Qh0stM4N** [comment]
@MannRodighan it looks very interesting. I will work on it. I think I need to do a deep research. 

I will remove unnecessary parts from your message for your safety.
SystemInfo gives a very detailed query result and your comment is open to everyone.

**Comment by MannRodighan** [comment]
Alright. Many thanks and good luck ! I'm absolute garbarge in programming and trying to find a solution to my problem gave me and some other people who tried to help me a huge headache lol.

**Comment by Qh0stM4N** [comment]
Errors triggered Pillow modules. i have used python 32 bit. but you python CLI maybe 64 bit versions. 
try this solutions.
https://stackoverflow.com/questions/30965365/importerror-dll-load-failed-1-is-not-a-valid-win32-application-for-imaging-m

**Comment by RogerioBlanco** [comment]
Feedback?

**Comment by Qh0stM4N** [comment]
closed issue end of active life. Potential solution: https://github.com/RogerioBlanco/PixelCanvasBot/issues/62#issuecomment-336831602
