### ISSUE TITLE
No module named request.

### ISSUE THREAD

**Issue by WordedPuppet** [RogerioBlanco/PixelCanvasBot#63]
I keep trying to use the program, but I keep getting an error in "pixelcanvasio.py" saying "No module named request."

**Comment by RogerioBlanco** [comment]
What version you are using?

**Comment by WordedPuppet** [comment]
Python 2.7.1.3

**Comment by Qh0stM4N** [comment]
try to run `python ./setup.py` getting result.

and type save to local this code 

> c:\\yoursFileName.py


```
import pip
installed_packages = pip.get_installed_distributions()
installed_packages_list = sorted(["%s==%s" % (i.key, i.version)
     for i in installed_packages])
print(installed_packages_list)
```
run at for example `python yoursFileName.py`

**Comment by RogerioBlanco** [comment]
Feedback?

**Comment by Qh0stM4N** [comment]
closed issue end of active life. Ptential solution: Reinstal run at setup.py or ReInstal python
