### ISSUE TITLE
"bash: python: command not found" I think I'm doing something wrong.. Can someone tell me?

### ISSUE THREAD

**Issue by Ungreatly** [RogerioBlanco/PixelCanvasBot#64]
I'm very new to GitHub, I only came here for the PixelCanvas.io bots.
With that being said I have come across problems meanwhile trying to follow the instructions.
![image](https://user-images.githubusercontent.com/12828465/32132982-b7afe88c-bbce-11e7-8f16-39e8c6186739.png)
Can somebody please help?
Yes, my image is called image.png
AND I'm and the coordinates
So.. What am I doing wrong?

**Comment by Ungreatly** [comment]
I do have the latest version of python

**Comment by Qh0stM4N** [comment]
@Ungreatly Your OS = linux or winNT.
this terminal look at gitbash linux terminal emulations.
if R U use windows try it winkey+R type 'cmd' `cd yoursPath` `python ./setup.py` `python ./main.py [yours parameters]`

**Comment by Ungreatly** [comment]
https://gyazo.com/a2eb2769c74535d6caa7cc5a4976e531

**Comment by Ungreatly** [comment]
wait i did it wrong lemme try again

**Comment by Ungreatly** [comment]
https://gyazo.com/18962dd26abdc8a8aaad40c79de87019
ehhhhhhh

**Comment by Qh0stM4N** [comment]
@Ungreatly okay pls enter on cmd this command need yours result.
echo %PATH%
check yours python path.

**Comment by Ungreatly** [comment]
https://gyazo.com/c0de6410d31299cfe97f4247919cdcb2
Cannot seem to find Python, used CTRL + F to find it but it isn't there..

**Comment by Ungreatly** [comment]
So that seems to be the problem to this whole thing.

**Comment by Qh0stM4N** [comment]
okey U need a adding python yours System path 
referance this answer 
https://stackoverflow.com/a/4855685
`C:\\python27\` change to  `C:\\YoursPythonPath\`

And try this Cmd 

> python --version

**Comment by Ungreatly** [comment]
Thank you so much for your help!
But, I still have one issue.
It says IOError: [Errno 2] No such file or directory: 'zoinks.jpg'
So... do I have to put the image in a certain folder?
Thanks!

**Comment by RogerioBlanco** [comment]
You need to put the path of your image. Ex:
C:\Temp\zoinks.jpg
OR if you image are in the bot folder you just need to put the path relative the main folder. Ex:
img\zoinks.jpg

**Comment by Ungreatly** [comment]
Generating converted image.
Alright I think I'm done with this.

**Comment by Ungreatly** [comment]
I'll just wait for the converted image.

**Comment by Ungreatly** [comment]
Saved image cache file, Loading Now...
Alright, this seems good

**Comment by Ungreatly** [comment]
KeyError: 'waitSeconds'
EHHHH NEVERMIND

**Comment by Ungreatly** [comment]
Fatal Python error: PyImport_GetModuleDict: no module dictionary!
this might help you solve they KeyError bug

**Comment by Qh0stM4N** [comment]
@Ungreatly need your  result, please
`python --version`

**Comment by Qh0stM4N** [comment]
#60

**Comment by Qh0stM4N** [comment]
closed. I think it would be appropriate to move there once a similar topic has been opened.
@Ungreatly issues move at #60
