### ISSUE TITLE
Token asked after 30 minutes

### ISSUE THREAD

**Issue by Ailothaen** [RogerioBlanco/PixelCanvasBot#65]
Hi,

I tried to use the script to automatize the drawing of an image.
At first, the bot ran without problems, but however, after like 30 minutes, Pixelcanvas prompted me to generate a new token (by clicking in my browser) : 

> 16:51:15 ->Somebody updated -3729,-1779 with dark turquoise color
> 16:51:15 ->You painted dark turquoise in the -3729,-1779
> 16:51:15 ->Waiting 10.398 seconds
> [+++++++++++++++++++++]
> 16:51:27 ->Oh no, it is need to provide a token. You need to enter in pixelcanvas.io and click in an pixel. >> 16:51:27 ->"Have you already clicked on a pixel in pixelcanvas.io? y/n:Traceback (most recent call last):
>   File "main.py", line 62, in <module>
>     main()
>   File "main.py", line 58, in main
>     run()
>   File "main.py", line 56, in run
>     if raw_input(I18n.get('token_resolved')) == 'y':
> IOError: [Errno 9] Bad file descriptor

So I ask, is it a normal thing about the script ? Or is there something I am doing wrong, or the Pixelcanvas "anti-spam" system changed?

Thanks in advance.

**Comment by RogerioBlanco** [comment]
The last 7 lines isn't right, but yeah the PixelCanvas have a anti-bot system, that every 30 minutes they use a captcha.

**Comment by Qh0stM4N** [comment]
https://www.google.com/recaptcha/intro/invisible.html
I do not even think about breaking as you can understand :)
It does not mean it can not be done. We are just having fun. But even if we did, it was wrong to share it everywhere. It could be used for bad purposes.

**Comment by Ailothaen** [comment]
I never used "normally" pixelcanvas for more than 30 minutes, so I didn't know you have to provide the captcha again. I thought the token was relative to the fingerprint or something...
Damn, I feel dumb now. But thanks for the fast feedback.
