### ISSUE TITLE
Help me.

### ISSUE THREAD

**Issue by Breno533** [RogerioBlanco/PixelCanvasBot#66]
I was asking the help of a friend to make the bot, because I do not know how to use the site very well, because I do not know how to speak English very well, and he told me that after doing everything related to the notepad, put in the phyton folder , I would have to do the setup of '' get-pip-py '', then I reinstalled, I tried several versions (of phyton) and did not see this option (get-pip-py) and I do not know the What can you do, can you help me?

**Comment by Qh0stM4N** [comment]
setup reuired packages with pip. get-pip-py allready included bot project.
Try to `python ./setup.py` once time retry start a bot.

**Comment by Breno533** [comment]
I think you did not understand very well, I meant, I meant that when down phyton, in his folder when installed does not appear any setup.py, things related of type.

**Comment by Breno533** [comment]
Maybe I'm not finding it inside another folder inside the Phyton folder, but everything I've tried for nothing found .py

**Comment by Breno533** [comment]
Look, there's nothing .py here.
![image](https://user-images.githubusercontent.com/33303703/32411069-8f1de730-c1b8-11e7-9729-6f87de95eaff.png)

**Comment by Ungreatly** [comment]
In the CMD do 
git clone -b master --single-branch --depth 10 https://github.com/RogerioBlanco/PixelCanvasBot.git
because the setup.py file isn't in the python folder but in the pixelcanvasbot folder
It should download PixelCanvasBot into the documents section on ur pc

**Comment by Breno533** [comment]
I'm not understanding very well what it is to do, are you Brazilian or do you have a personal discord?

**Comment by RogerioBlanco** [comment]
Breno, pode escrever por aqui. Sou brasileiro.
