### ISSUE TITLE
How do let the bot know I've provided a token?

### ISSUE THREAD

**Issue by Ungreatly** [RogerioBlanco/PixelCanvasBot#67]
>> 22:22:36 ->Oh no, it is need to provide a token. You need to enter in pixelcanvas.io and click in an pixel.
>> 22:22:36 ->"Have you already clicked on a pixel in pixelcanvas.io? y/n:

ive tried typing in y but it doesnt work... any help???

**Comment by ZeedyPixel** [comment]
@Ungreatly you need to go to pixelcanvas and pass the captcha, then u back to cmd and put the "y"

**Comment by Ungreatly** [comment]
problem is it says it isnt a command

**Comment by Recruiter2** [comment]
restart everything over
