### ISSUE TITLE
Halp

### ISSUE THREAD

**Issue by Jh0w** [RogerioBlanco/PixelCanvasBot#68]
Tentei executar o bot mas ocorre o seguinte erro:
![prompt](https://user-images.githubusercontent.com/35577424/35117615-50c96baa-fc76-11e7-8b08-cf539887ea3a.png)

**Comment by Jh0w** [comment]
Estou fazendo algo errado? Como posso corrigir?

**Comment by Qh0stM4N** [comment]
Need your command result 
`python --version`
`wmic os get osarchitecture`
`python -m pip list`

and installed python version (32bit or 64bit)?

I can not do anything without knowing them.
I suggest remove the python. It will reinstall as 32 bit maybe.
English pls.

external wrong use `--sketch` mode sketch is not paramerter its a parameter value .  Replace this with `--draw_strategy sketch`

**Comment by Jh0w** [comment]
OS Architecture: 64 bits
Python Version: 2.7.14
PIP List: certifi (2017.11.5)
chardet 3.0.4
idna 2.6
olefile 0.44
Pillow 4.3.0
pip 9.0.1
pypng 0.0.18
PyQRCode 1.2.1
requests 2.18.4
setuptools 28.8.0
six 1.11.0
urllib3 1.22
websocket-client 0.44.0

I have Python 64 bits, but the installer i downloaded automatically sets python as 64 bits. How can i install a 32 bits version?

**Comment by Jh0w** [comment]
Nevermind. I installed a 32 bit version and its working now. Thanks!

**Comment by Qh0stM4N** [comment]
@Jh0w I'm aware of the problem, I've had a similar situation before.

> I suggest remove the python. It will reinstall as 32 bit maybe.

The 2.7 version of python is a bit stale, so simple problems arise, need to make some effort to upgrade to 3.* versions, but I do not care much because the problem is not caused by the bot code.
