### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by 4rm4g3dd0n** [RogerioBlanco/PixelCanvasBot#70]
I'm trying to use the bot, but a bug is happening here. 
Screenshot: 
![image](https://user-images.githubusercontent.com/22554335/39850385-659ed614-53e7-11e8-8e2a-353ee4ce0cbd.png)

//Windows 7
// Python 2.7

I've tried in Win10 but Python is crashing ¬¬

**Comment by Qh0stM4N** [comment]
@4rm4g3dd0n Your fingerprint is invalid. remove '$' charecter in fingerprint parameter.
You can test the bot status mode for fingerprint independently. Try 
```bash
python ./main.py -i youuimage.img -f 0d031548af58e4c45f5e455a87a --draw_strategy status -x 0 -y 0
```

**Comment by 4rm4g3dd0n** [comment]
Thx @Qh0stM4N My stupid mistake
