### ISSUE TITLE
string index out of range in bot.py

### ISSUE THREAD

**Issue by laundmo** [RogerioBlanco/PixelCanvasBot#71]
when trying to use a proxy, im experiencing this error: 
https://i.imgur.com/AOFbz5V.png

that doesnt happen when i dont use a proxy, then it works like normal

the command im using to start looks like this: `C:\Python27\python.exe ./main.py -i %1 -f %2 -x %3 -y %4 --draw_strategy %5 --proxy_url %6 --colors_not_overwrite  1 2  4 5 6 7 8 9 10 11 12 13 15`

my proxy works, and it doesnt need authentification. the error occures wihtout the proxy auth argument and wiht `--proxy_auth :` (empty auth)

windows 10 / 64bit
python 2.7.15 (just updated)

**Comment by Qh0stM4N** [comment]
Offline proxy or bad address need port not use only ip. 
test https://free-proxy-list.net/ pick any ip
`--proxy_url 123.123.123.123:8181`

**Comment by laundmo** [comment]
1. i have tested the proxy using the FoxyProxy extension, and it works flawless

2. i am using both ip and port in the format shown by you: '111.111.111.111:2222'

**Comment by Qh0stM4N** [comment]
I guess will completely rewrite the proxy support. Missing an error message is not a problem, it can be handled.
