### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by jollyjester** [RogerioBlanco/PixelCanvasBot#77]
File "./setup.py", line 7
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

**Comment by Qh0stM4N** [comment]
Check your python version type `python --version` command;  reqires 2.7

**Comment by Recruiter2** [comment]
hi how do I add proxy I tryed --proxy_url XX.228.202.58:53281 when the bot was already working is that ok?

**Comment by Recruiter2** [comment]
it doesn't seem to add more pixels

**Comment by Recruiter2** [comment]
python ./main.py --proxy_xx.228.202.58:53281
came up with this

**Comment by Recruiter2** [comment]
still doesn't work maybe the proxy is banned?

**Comment by Qh0stM4N** [comment]
@Recruiter2 I gave your answer https://github.com/RogerioBlanco/PixelCanvasBot/issues/78#issuecomment-419861101
