### ISSUE TITLE
Pixelcanvas might've changed their api again

### ISSUE THREAD

**Issue by Yelinz** [RogerioBlanco/PixelCanvasBot#88]
```bash
Traceback (most recent call last):
  File ".\main.py", line 103, in <module>
    main()
  File ".\main.py", line 84, in main
    bot.init()
  File "F:\stuff\PixelCanvasBot\src\bot.py", line 32, in init
    self.canvas = self.setup_canvas()
  File "F:\stuff\PixelCanvasBot\src\bot.py", line 98, in setup_canvas
    canvas.update(actual_x, actual_y, EnumColor.index(raw[index] >> 4))
IndexError: bytearray index out of range
```

**Comment by Yelinz** [comment]
Well it turns out the servers were just down for a few weeks

**Comment by Qh0stM4N** [comment]
@Yelinz Can you confirm whether it is still working? Now i can't follow because doesnt contribute to any pixart. If think that still not working pls reopen this issue.

**Comment by Yelinz** [comment]
I tried to use the bot and it didn't work, so i think the API/ Validation actually changed and the downtime was for those changes. The Error is still the same.

**Comment by Pr0phet-of-Fear** [comment]
I just started getting this issue. Website works fine. I'm not banned, because I can draw manually on the website; but every time I run the bot I get the same exact error message as OP. Might have something to do with them changing things around for April Fools yesterday?

**Comment by Yelinz** [comment]
Same here on April 1st it worked, but now there is something wrong.

**Comment by Yelinz** [comment]
Light debugging revealed presumably the problem.

If we use ipdb and look into the bytearray it says this:
`bytearray(b'{"error":"FUCK YOU "}')`

I am not joking.

**Comment by Qh0stM4N** [comment]
> `bytearray(b'{"error":"FUCK YOU "}')`
> 
> I am not joking.
@Yelinz You not, but @arkeros :)

**Comment by RogerioBlanco** [comment]
Arkeros changed the way that need to download the bigchunck. 
So you guys just need update the bot to work well.
