### ISSUE TITLE
Been getting this error since yesterday.

### ISSUE THREAD

**Issue by Pr0phet-of-Fear** [RogerioBlanco/PixelCanvasBot#92]
![b0bb57d9c07c9ca573279d8a2c5effe7](https://user-images.githubusercontent.com/49212464/56257044-01532600-6099-11e9-874f-86a4933f38de.png)

**Comment by Boboss74** [comment]
Probably related to the https and wss migration

**Comment by Qh0stM4N** [comment]
@Boboss74 like  #91 sorry can not yet look at the problem busy today,
 i handle this issue in tomorrow.

**Comment by Pr0phet-of-Fear** [comment]
Is this being worked on? It has been 20 days (19 giving you the benefit of the doubt) since you said that you would work on this "tomorrow", and there have been no updates either on your progress (or lack thereof), or to the project itself. @Qh0stM4N

**Comment by Boboss74** [comment]
@Pr0phet-of-Fear
This is a free tool developed by @Qh0stM4N during his free time.
@Qh0stM4N is not your employee, he owes you nothing.

You could have really ask news in a different and nicer way.
In fact, you still can try.

**Comment by Pr0phet-of-Fear** [comment]
I feel like you really misinterpreted the tone I was going for; and I understand that I am not entitled to anything, _but_ it is quite annoying when someone says they are going to do something, and then just don't, without any explanation or statement that they have changed their mind.

I'm sure Qh0st intended to work on it then just forgot, or something similar; and I'm not upset. I was just looking for news.

**Comment by Boboss74** [comment]
Ok, I really misinterpreted the tone, sorry ^^'''

Btw, you should have a look here 😉
https://github.com/RogerioBlanco/PixelCanvasBot/network
